
# Site settings
title: Seki's note
description: Katsutoshi Seki's personal note.
# author: <a href="http://wwws.amazon.co.jp/-/e/B00ADGVC1W">関 勝寿</a>
author: <a href="https://sekika.github.io/toyo/">関 勝寿</a>
author-en: <a href="https://scholar.google.com/citations?user=Gs_ABawAAAAJ">Katsutoshi Seki</a>
baseurl: "" 
url: "https://sekika.github.io" 
repository: "https://github.com/sekika/sekika.github.io"

# Versions of JavaScript
# Last update on 2024-05-13
bootstrap-version: "5.3.3" # Bootstrap http://getbootstrap.com/getting-started/
highlight-version: "11.9.0" # highlight.js https://highlightjs.org/
katex-version: "0.16.10" # KaTeX https://github.com/Khan/KaTeX/releases
pyodide-version: "0.25.1" # Pyodide https://pyodide.org/en/stable/project/changelog.html
plotly-version: "2.32.0" # Plotly https://plotly.com/javascript/getting-started/
jquery-version: "3.7.1" # jQuery https://jquery.com/download/
pako-version: "2.1.0" # pako https://cdnjs.com/libraries/pako

# Bootstrap theme
bootstrap-theme: "flatly" # https://bootswatch.com/

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed

# pagination
paginate: 10
pagenate_path: "page:num"

# highlighter: "rouge"

exclude: [vendor]
